[tool.poetry]
name = "vana-inference"
version = "0.1.0"
description = "FastAPI-based inference/training engine for Vana"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.0"
uvicorn = "^0.27.0"
pydantic = "^2.6.0"
unsloth = "^0.3.0"
torch = ">=2.0.0"
transformers = "^4.38.0"
accelerate = "^0.27.0"
bitsandbytes = "^0.41.0"
peft = "^0.8.0"
datasets = "^2.16.0"
sqlalchemy = "^2.0.0"
sqlite3-api = "^0.1.0"
tiktoken = "^0.5.0"  # Added for OpenAI-compatible token counting

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
isort = "^5.12.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"