name: Build and Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: |
            my-inference-job:${{ github.run_number }}
            my-inference-job:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export image to file
        run: |
          docker save my-inference-job:latest | gzip > my-inference-job-${{ github.run_number }}.tar.gz

      - name: Generate release body
        run: |
          echo "Image SHA256: $(sha256sum my-inference-job-${{ github.run_number }}.tar.gz | cut -d' ' -f1)" >> release_body.txt

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: my-inference-job-image
          path: my-inference-job-${{ github.run_number }}.tar.gz

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body_path: release_body.txt
          draft: false
          prerelease: false
          files: |
            ./my-inference-job-${{ github.run_number }}.tar.gz

      - name: Log build result
        if: always()
        run: |
          if [ ${{ job.status }} == "success" ]; then
            echo "Build and release completed successfully"
          else
            echo "Build and release failed"
          fi